---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt: 
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  vars:
    pip_install_packages:
      - name: docker-compose

  roles: 
    - geerlingguy.pip
    - geerlingguy.docker
    - ansible-role-gickup
